version: '2'

services:
  mysql:
    image: "mysql/mysql-server"
    environment:
      - MYSQL_ROOT_PASSWORD=root@passwd
      - MYSQL_DATABASE=mapsa97
      - MYSQL_ROOT_HOST=%
    volumes:
      - $PWD/data/${APP_NAME}:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root@passwd
    restart: always
    ports:
      - 9500:80

